add identity base abi
iden3/contracts-abi pull request #4
Opened 2023-06-21 15:36 UTC by ilya-korotya

2023-06-21 16:47 UTC, vmidyllic approved these changes

2023-06-21 21:47 UTC, demonsh requested changes
Function getRevocationStatus(nonce) must be modified to getRevocationStatus(id, nonce) according to the initial agreement of a common interface for revocation flow. 
First should be fixed SC

2023-06-23 12:15 UTC, demonsh approved these changes

2023-07-26 08:36 UTC, OBrezhniev approved these changes

2023-07-26 08:47 UTC, merged